class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
init_args:
  dirpath: null
  filename: '{epoch}-{step}-{val_kendall:.3f}'
  monitor: val_kendall
  verbose: True
  save_last: False
  save_top_k: 2
  mode: max
  auto_insert_metric_name: True
  save_weights_only: True
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 1
  save_on_train_epoch_end: null
