class_path: pytorch_lightning.trainer.trainer.Trainer
init_args:
  accelerator: null
  accumulate_grad_batches: 2
  amp_backend: native
  amp_level: O0
  auto_lr_find: False
  auto_scale_batch_size: False
  auto_select_gpus: False
  benchmark: False
  check_val_every_n_epoch: 1
  default_root_dir: null
  deterministic: True
  fast_dev_run: False
  flush_logs_every_n_steps: 100
  gpus: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  log_gpu_memory: null
  log_every_n_steps: 10
  prepare_data_per_node: True 
  process_position: 0 
  progress_bar_refresh_rate: null
  profiler: null
  overfit_batches: 0.0
  plugins: null
  precision: 32
  max_epochs: 3
  min_epochs: 1
  max_steps: null
  min_steps: null
  max_time: null
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 10
  reload_dataloaders_every_epoch: False
  replace_sampler_ddp: True
  resume_from_checkpoint: null
  sync_batchnorm: False
  terminate_on_nan: False
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
  weights_summary: top
  move_metrics_to_cpu: True
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: True
